# source ; https://medium.com/analytics-vidhya/advanced-numpy-218584c60c63

# source ; https://medium.com/analytics-vidhya/numpy-the-very-basics-6ce19206ee22

# NumPy Attributes

    1. ndim - Number of dimensions.
    2. shape - The size of each dimension.
    3. size - The total size of the array.
    4. dtype - The data type of array elements.
    5. itemsize - Byte size of each array element.
    6. nbytes - Total size of the array. It is equal to itemsize times size.

### My weakness slicing technique

In [83]:
x = np.arange(10)

x

x[:5]

x[5:]

x[4:7]

x[::2]

x[1::2] # every other element, starting at index 1

x[::-1] # all elements, reversed

x[5::-2] # reversed every other from index 5

array([5, 3, 1])

### My weakness Multidimensional array slicing technique

In [89]:
a = np.array( [[2,3,5,8,7],
              [1,2,3,4,5],
              [5,3,1,7,6]])
# 2 rows 3 columns
a[:2,:3]

# 3 rows 2 columns
a[:3,:2]

#reverse the element from both rows and columns.
a[::1, ::-1]


array([[7, 8, 5, 3, 2],
       [5, 4, 3, 2, 1],
       [6, 7, 1, 3, 5]])

## Array concatenation and splitting

### concatenate, vstack , hstack, dstack

In [100]:
a= np.array([1,2,3,4])

b=np.array([5,6,7,8]) 

c=np.array([[9,8,7,6],
            [5,4,3,2]])

d=np.array([[5,4],
            [2,3]])

In [101]:
# concatenate
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
# vstack
np.vstack([a,c])

array([[1, 2, 3, 4],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [105]:
# hstack
np.hstack([c,d])

array([[9, 8, 7, 6, 5, 4],
       [5, 4, 3, 2, 2, 3]])

In [4]:
import numpy as np

## ufuncs

In [6]:
import numpy as np
np.random.seed(0)

values = np.random.randint(1, 10, size=10)
output = np.empty(len(values)) # empty array to store output
for i in range(len(values)):
    output[i] = values[i]**2
output

array([36.,  1., 16., 16., 64., 16., 36.,  9., 25., 64.])

In [17]:
#Ufunc operations are extremely flexible.
np.random.seed(0)

values = np.random.randint(1, 10, size=10)
values**2

array([36,  1, 16, 16, 64, 16, 36,  9, 25, 64], dtype=int32)

## Trignometric functions

In [19]:
theta = np.linspace(0, np.pi, 5)

print('theta = ', theta)
print('sin(theta) = ', np.sin(theta))
print('cos(theta) = ', np.cos(theta))
print('tan(theta) = ', np.tan(theta))

theta =  [0.         0.78539816 1.57079633 2.35619449 3.14159265]
sin(theta) =  [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
cos(theta) =  [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]
tan(theta) =  [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16]


## Inverse trignometric functions

In [20]:
x = np.array([-1, 0, 1])
print('x = ', x)
print('arcsin(x) = ', np.arcsin(x))
print('arccos(x) = ', np.arccos(x))
print('arctan(x) = ', np.arctan(x))

x =  [-1  0  1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


## Exponents

In [24]:
x = np.arange(1, 4)
print('x = ', x)
print('e^x = ', np.exp(x))
print('2^x = ', np.exp2(x))
print('3^x = ', np.power(3 , x))

x =  [1 2 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


## Logarithms

In [30]:
x = np.random.randint(1, 4, size=4) # size meaning is just how deginate counts that value
print('x =', x)
print('ln(x) =', np.log(x))
print('log2(x) =', np.log2(x))
print('log10(x) =', np.log10(x))

x = [1 1 2 3]
ln(x) = [0.         0.         0.69314718 1.09861229]
log2(x) = [0.        0.        1.        1.5849625]
log10(x) = [0.         0.         0.30103    0.47712125]


## Aggregation

mean and standard deviation

In [31]:
# numpy version
array = np.random.random(10)
print(array)
print('Summation:', np.sum(array))
print('Min:', np.min(array))
print('Max:', np.max(array))

[0.14035078 0.87008726 0.47360805 0.80091075 0.52047748 0.67887953
 0.72063265 0.58201979 0.53737323 0.75861562]
Summation: 6.082955146266993
Min: 0.14035078041264515
Max: 0.8700872583584364


In [32]:
# array version
array = np.random.random(10)
print(array)
print('Summation:', array.sum())
print('Min:', array.min())
print('Max:', array.max())

[0.10590761 0.47360042 0.18633234 0.73691818 0.21655035 0.13521817
 0.32414101 0.14967487 0.22232139 0.38648898]
Summation: 2.9371533191743384
Min: 0.10590760718779213
Max: 0.7369181771289581




### The one question you can raise is why to use NumPy aggregate functions when these functions are already inbuilt in Python ( sum(), min(), max(), etc).
### Of course, the difference is NumPy functions are much faster but more importantly NumPy functions are aware of dimensions. Python functions behave differently on multidimensional arrays.

In [33]:
array = np.arange(10).reshape(2,5)
print(array)
print('Summation:', sum(array))

[[0 1 2 3 4]
 [5 6 7 8 9]]
Summation: [ 5  7  9 11 13]


##     Multidimensional aggregates

In [34]:
np.random.seed(0)
marks = np.random.randint(20, 100, size=(4,6))
print(marks)
print('Min marks in each subject:', marks.min(axis=0))
print('Max marks in each subject:', marks.max(axis=0))
print('Total marks in each subject:', marks.sum(axis=1))

[[64 67 84 87 87 29]
 [41 56 90 32 78 85]
 [59 66 57 45 97 92]
 [29 40 89 99 67 84]]
Min marks in each subject: [29 40 57 32 67 29]
Max marks in each subject: [64 67 90 99 97 92]
Total marks in each subject: [418 382 416 408]


## Broadcasting

__Perform unfuncs on arrays of different sizes.__

In [40]:
m = np.ones((3, 3))
print('m: \n',m)
print('Shape of m:', m.shape)
n = np.array([0,1,2])
print('n:',n)
print('Shape of n:',n.shape)
add = m + n
print('m + n: \n',add)
print('Shape of m + n:', add.shape)

m: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape of m: (3, 3)
n: [0 1 2]
Shape of n: (3,)
m + n: 
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
Shape of m + n: (3, 3)


In [42]:
m = np.arange(3)
n = np.arange(3).reshape(3,1)
print('m: \n',m)
print('Shape of m:',m.shape)
print('n: \n',n)
print('Shape of n:',n.shape)
add = m + n
print('m + n: \n', add)
print('Shape of m + n:', add.shape)

m: 
 [0 1 2]
Shape of m: (3,)
n: 
 [[0]
 [1]
 [2]]
Shape of n: (3, 1)
m + n: 
 [[0 1 2]
 [1 2 3]
 [2 3 4]]
Shape of m + n: (3, 3)


## 3 Rules for Broadcasting

m = np.arange(3).reshape((3,1))

n = np.arange(3)

m.shape = (3, 1)

n.shape = (3,)

- By rule 1, if two arrays deffer in their shape the array with lesser shape should be padded with ‘1’ on it's left side.

m.shape => (3, 1)

n.shape => (1, 3)
- By rule 2, if still the shape of two arrays do not match then each array whose dimension is equal to 1 should be broadcasted to match the shape of another array.

m.shape => (3, 3)

n.shape => (3, 3)

## Masking

Masking is a method used extensively in the data processing. It allows us to extract, count, modify or manipulate values in an array based on certain criteria, these criteria are specified using comparison operators and boolean operators.

In [50]:
np.random.seed(0)
x = np.random.randint(10, size=(3,4))
print('Original');print(x)
print('Values of x less than 5')
print(x[x<5])

Original
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
Values of x less than 5
[0 3 3 3 2 4]


## Fancy indexing
Fancy indexing is similar to normal indexing as we already know. The only difference is we pass an array of indices here. This advanced version of indexing allows quick access and/or modification of complicated subsets of an array.

In [71]:
# Suppose we want to access elements at index 2, 5, and 9 of an array, the old school method would be [x[2], x[5], x[9]]. This can we simplified using fancy indexing.
np.random.seed(42)
x = np.random.randint(100, size = 10)
print(x)
print(x[[2, 5, 9]])

[51 92 14 71 60 20 82 86 74 74]
[14 20 74]


## Array sorting
np.sort is a more efficient sorting function than Python’s built-in sort function. 

__Additionally, np.sort is aware of dimensions.__ Let’s see a few flavors of the NumPy sorting function.

In [73]:
# Simple sorting
x = np.random.randint(10, size = 10)
print(x)
print('Sorted array :', np.sort(x))

# Indices of the sorted array
print('Indices of the sorted array :', np.argsort(x))

# Using sort method
x.sort()
print('In-place sorting :' , x)

[5 1 4 0 9 5 8 0 9 2]
Sorted array : [0 0 1 2 4 5 5 8 9 9]
Indices of the sorted array : [3 7 1 9 2 0 5 6 4 8]
In-place sorting : [0 0 1 2 4 5 5 8 9 9]
